"""
critic.py - Critic agent for agentic-v2.

The Critic evaluates specialist agent responses before they reach the user.
It checks whether the answer is adequately supported by the retrieved chunks
and whether obvious gaps exist.

Why a Critic agent?
Specialist agents generate answers from whatever chunks they receive.
If retrieval missed key documents, the specialist doesn't know -- it
just works with what it has. The Critic has visibility into both the
chunks AND the answer, so it can spot mismatches: "the question asked
about FEP controls but all chunks are from SCADA docs."

Why gemma4:e4b instead of 31B?
The Critic does structured evaluation, not deep reasoning. E4B is fast
and cheap for this task. We don't want the Critic to double the response
time -- it should add only a few seconds.

PASS/REJECT semantics:
- PASS: answer is adequately supported, send it to the user
- REJECT: answer has gaps or wrong sources, flag for iterative refinement
  (Step 4 of agentic-v2 will use the feedback to re-retrieve and retry)

Fail-safe: if the model returns an unparseable response, default to PASS.
A broken Critic must never block a valid answer from reaching the user.
"""

import requests
from src.config import OLLAMA, MODELS


CRITIC_PROMPT = """You are a quality evaluator for a document assistant system.
You will receive: a user query, the document excerpts used to answer it,
and the draft answer generated by the assistant.

Your job is to evaluate whether the answer adequately addresses the query
based on the provided document excerpts.

Evaluation criteria:
1. SOURCE RELEVANCE: Are the document excerpts actually relevant to the query?
   If the query asks about System A but all excerpts are from System B docs,
   that is a source mismatch.
2. ANSWER COMPLETENESS: Does the answer address the core of what was asked?
   Minor gaps are acceptable. Major omissions are not.
3. CITATION SUPPORT: Are the key claims in the answer supported by the excerpts?

Respond in EXACTLY this format (two lines, nothing else):
VERDICT: PASS
FEEDBACK: One sentence explaining your verdict.

Or if rejecting:
VERDICT: REJECT
FEEDBACK: One sentence describing the specific gap or problem.

VERDICT must be exactly PASS or REJECT. No other values."""


def parse_critic_response(raw: str) -> tuple[str, str]:
    """
    Parse the critic model response into verdict and feedback.

    Returns:
        (verdict, feedback)
        verdict: "PASS" or "REJECT"
        feedback: explanation string

    Defaults to PASS if response is unparseable -- broken critic
    must never block a valid answer.
    """
    verdict = "PASS"
    feedback = "Critic response unparseable — defaulting to PASS."

    for line in raw.strip().splitlines():
        line = line.strip()
        if line.upper().startswith("VERDICT:"):
            val = line.split(":", 1)[1].strip().upper()
            if val in ("PASS", "REJECT"):
                verdict = val
        elif line.upper().startswith("FEEDBACK:"):
            feedback = line.split(":", 1)[1].strip()

    return verdict, feedback


def critique(query: str,
             chunks: list,
             answer: str,
             model: str = None) -> dict:
    """
    Evaluate a specialist agent response for quality and source relevance.

    Args:
        query: The original user question
        chunks: The document excerpts used to generate the answer
        answer: The draft answer from the specialist agent
        model: Optional model override (defaults to router_llm / e4b)

    Returns:
        {
            "verdict": "PASS" or "REJECT",
            "feedback": "explanation string",
        }
    """
    if not chunks:
        return {
            "verdict": "REJECT",
            "feedback": "No document chunks were retrieved — cannot verify answer."
        }

    # Build excerpt summary for the critic (truncated to keep prompt short)
    excerpt_lines = []
    for i, chunk in enumerate(chunks, 1):
        source = chunk.get("source", "unknown")
        page = chunk.get("page", "?")
        preview = chunk.get("text", "")[:200].replace("\n", " ")
        excerpt_lines.append(f"[{i}] {source} p.{page}: {preview}...")
    excerpts_text = "\n".join(excerpt_lines)

    # Truncate answer for critic prompt -- critic doesn't need the full answer
    answer_preview = answer[:1000] if len(answer) > 1000 else answer

    prompt = f"""{CRITIC_PROMPT}

--- USER QUERY ---
{query}

--- DOCUMENT EXCERPTS USED ---
{excerpts_text}

--- DRAFT ANSWER ---
{answer_preview}

Evaluate now. Respond with exactly two lines: VERDICT and FEEDBACK."""

    try:
        response = requests.post(
            f"{OLLAMA['base_url']}/api/generate",
            json={
                "model": model or MODELS["router_llm"],
                "prompt": prompt,
                "stream": False,
                "options": {
                    "temperature": 0.0,
                    "num_predict": 200,
                }
            },
            timeout=OLLAMA["timeout_seconds"]
        )
        response.raise_for_status()
        raw = response.json()["response"].strip()
        print(f"  [Critic] Raw response: {raw[:100]}")

    except Exception as e:
        print(f"  [Critic] Error: {e} — defaulting to PASS")
        return {
            "verdict": "PASS",
            "feedback": f"Critic error: {str(e)} — defaulting to PASS."
        }

    verdict, feedback = parse_critic_response(raw)
    print(f"  [Critic] Verdict: {verdict} | {feedback}")

    return {
        "verdict": verdict,
        "feedback": feedback
    }
